### open transaction
GRPC localhost:8001/api.GritApi/OpenTransaction

{
  "type": "WRITE"
}

### add vertex

GRPC localhost:8001/api.GritApi/AddVertex

{
  "txId": "1",
  "vertexId": {
    "type": "comp",
    "id": 2134
  }
}

### add vertex on OTHER instance

GRPC localhost:8002/api.GritApi/AddVertex

{
  "txId": "1",
  "vertexId": {
    "type": "comp",
    "id": 1234
  }
}

### add edge

GRPC localhost:8001/api.GritApi/AddEdge

{
  "txId": "1",
  "label": "ye-vertex",
  "fromVertexId": {
    "type": "comp",
    "id": 2134
  },
  "toVertexId": {
    "type": "comp",
    "id": 1234
  }
}

### open read tx

GRPC localhost:8002/api.GritApi/OpenTransaction

{
  "type": "READ"
}

### read vertices before commit

GRPC localhost:8002/api.GritApi/GetVerticesByType

{
  "txId": "2",
  "type": "comp"
}

### commit the mutations

GRPC localhost:8001/api.GritApi/Commit

{
  "txId": "1"
}

### open read tx after commit

GRPC localhost:8002/api.GritApi/OpenTransaction

{
  "type": "READ"
}

### read vertices after commit

GRPC localhost:8002/api.GritApi/GetVerticesByType

{
  "txId": "3",
  "type": "comp"
}

### read vertices in original snapshot

GRPC localhost:8002/api.GritApi/GetVerticesByType

{
  "txId": "2",
  "type": "comp"
}

### read edges

GRPC localhost:8002/api.GritApi/GetEdges

{
  "txId": "3",
  "vertexId": {
    "type": "comp",
    "id": "2134"
  }
}
