### open transaction
GRPC localhost:8000/api.GritApi/OpenTransaction

{
  "type": "WRITE"
}

### add vertex

GRPC localhost:8000/api.GritApi/AddVertex

{
  "txId": "2",
  "vertexId": {
    "type": "comp",
    "id": 2134
  }
}

### add label

GRPC localhost:8000/api.GritApi/AddLabel

{
  "txId": "2",
  "vertexId": {
    "type": "comp",
    "id": 2134
  },
  "label": "ye-label"
}


### add other vertex

GRPC localhost:8000/api.GritApi/AddVertex

{
  "txId": "2",
  "vertexId": {
    "type": "comp",
    "id": 1234
  }
}

### add edge

GRPC localhost:8000/api.GritApi/AddEdge

{
  "txId": "2",
  "label": "ye-vertex",
  "fromVertexId": {
    "type": "comp",
    "id": 2134
  },
  "toVertexId": {
    "type": "comp",
    "id": 1234
  }
}

### open read tx

GRPC localhost:8000/api.GritApi/OpenTransaction

{
  "type": "READ"
}

### read vertices before commit

GRPC localhost:8000/api.GritApi/GetVerticesByType

{
  "txId": "3",
  "type": "comp"
}

### commit the mutations

GRPC localhost:8000/api.GritApi/Commit

{
  "txId": "2"
}

### open read tx after commit

GRPC localhost:8000/api.GritApi/OpenTransaction

{
  "type": "READ"
}

### read vertices by type after commit

GRPC localhost:8000/api.GritApi/GetVerticesByType

{
  "txId": "6",
  "type": "comp"
}


### read vertices by label after commit

GRPC localhost:8000/api.GritApi/GetVerticesByLabel

{
  "txId": "9",
  "type": "comp",
  "labels": ["ye-label"]
}

### read vertices in original snapshot

GRPC localhost:8000/api.GritApi/GetVerticesByType

{
  "txId": "3",
  "type": "comp"
}

### read edges

GRPC localhost:8000/api.GritApi/GetEdges

{
  "txId": "3",
  "vertexId": {
    "type": "comp",
    "id": "2134"
  }
}
